In [136]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [137]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [138]:
vector.ndim

1

In [139]:
tensor = torch.tensor([1,2,3])
tensor
print(tensor, "*" , tensor)
print(f"Equals: {tensor * tensor}")



tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [140]:
torch.matmul(tensor, tensor)
tensor.ndim

1

In [141]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.29 ms, sys: 2.52 ms, total: 3.82 ms
Wall time: 12.2 ms


In [142]:
%%time
torch.dot(tensor, tensor)

CPU times: user 250 μs, sys: 123 μs, total: 373 μs
Wall time: 809 μs


tensor(14)

In [143]:
tendor_A = torch.tensor(([1,2],
                         [3,4],
                         [5,6]))
tensor_B = torch.tensor(([7,10],
                         [8,11],
                         [9,12]))
torch.mm(tendor_A, tensor_B.T) # .T - Transpozycja

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## FInding min and max values

In [144]:
x = torch.arange(0, 100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [145]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [146]:
torch.mean(x.type(torch.float32)) # wymaga float32


tensor(45.)

In [147]:

torch.sum(x)

tensor(450)

In [148]:
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [149]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [150]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [151]:
## reshaping stacking


In [152]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [153]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [154]:
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [155]:
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [156]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape
x_squeezed = x_reshaped.squeeze()

In [157]:
print(f"prev ternsor: {x_reshaped}")
print(f"new tensor: {x_reshaped.shape}")

prev ternsor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
new tensor: torch.Size([1, 9])


In [158]:
print(f"Prev target: {x_squeezed}")
print(f"New target: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nPrev target: {x_unsqueezed}")
print(f"New target: {x_unsqueezed.shape}")

Prev target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New target: torch.Size([9])

Prev target: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New target: torch.Size([1, 9])


In [159]:
# torch indexing
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [160]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [161]:
x[0, 0][0]

tensor(1)

In [162]:
x[:,:,1]

tensor([[2, 5, 8]])

In [163]:
x[:,1,1]

tensor([5])

In [164]:
x[0,0,:]

tensor([1, 2, 3])

In [165]:
x[:,2,2], x[:,:,2]

(tensor([9]), tensor([[3, 6, 9]]))

In [166]:
array = np.arange(1.,8.)
tensor = torch.from_numpy(array).type(torch.float32) # pamiętac aby zmieni typ na float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [167]:
tensor = torch.ones(7)


In [168]:
# random tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [169]:
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [170]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [171]:
x = torch.tensor([1,2,3], device="cpu")
print(x, x.device)

tensor([1, 2, 3]) cpu


In [172]:
x2 = tensor.to(device)
x2

tensor([1., 1., 1., 1., 1., 1., 1.])